name: Testing

on:
  push:
    branches:
      - "main"

  pull_request:
    paths:
      - "src/**"

    types:
      - opened
      - synchronize
      - reopened

jobs:
  visual_regression:
    name: Visual regression
    timeout-minutes: 30
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Workaround for detached HEAD for reg-suit
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "yarn"

      # https://github.com/yarnpkg/yarn/issues/4147
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Take screenshots
        run: yarn screenshot

      - name: Regression testing
        env:
          REG_S3_BUCKET_NAME: ${{ secrets.REG_S3_BUCKET_NAME }}
        run: yarn test:visual_regression
